print ('                                                          ')
print ('                                                          ')
print ('                                                          ')
print ('                                                          ')
print ('                                                          ')
print ('                   __________________                     ')
print ('                  /   _____  _____   \                    ')
print ('                 /   /  O  \/  O  \   \                   ')
print ('                 \   \_____/\_____/   /                   ')
print ('                  \________\/________/                    ')
print ('                  /          /\\\\\\\\                    ')
print ('                 |           |\\\\\\\\\                   ')
print ('                  \           \\\\\\\\\\                  ')
print ('                   \           \\\\\\\\                   ')
print ('                    \____________/\\\\                    ')
print ('                      _||_  _||_                          ')
print ('                                                          ')
print ('                                                          ')
